export const FONTS = {
  aalto:          '/fonts/aalto.otf',
  being:          '/fonts/being.otf',
  benzol:         '/fonts/benzol.otf',
  clashGrotesk:   '/fonts/clash-grotesk-variable.ttf',
  digital7Mono:   '/fonts/digital-7-mono.ttf',
  disket:         '/fonts/disket.ttf',
  generalSans:    '/fonts/general-sans.ttf',
  half:           '/fonts/half.otf',
  heming:         '/fonts/heming.ttf',
  humane:         '/fonts/humane-variable.ttf',
  jersey10:       '/fonts/jersey-10-regular.ttf',
  karmaticArcade: '/fonts/karmatic-arcade-regular.ttf',
  kodeMono:       '/fonts/kode-mono-vf.ttf',
  miratrix:       '/fonts/miratrix.otf',
  nippo:          '/fonts/nippo.ttf',
  obrazec:        '/fonts/obrazec.otf',
  pixelony:       '/fonts/pixelony.ttf',
  triakis:        '/fonts/triakis.otf',
  unknown:        '/fonts/unknown.otf',
  yeager:         '/fonts/yeager.otf',
};
