export const STRINGS = {
  digo:                 'Digo',
  refresh:              'Refresh',
  code:                 'Code',
  score:                'Score',
  preview:              'Preview',
  weights:              'Weights',
  examples:             'Examples',
  typography:           'Typography',
  sizes:                'Sizes',
  icons:                'Icons',
  neutral:              'Neutral',
  info:                 'Info',
  selected:             'Selected',
  noneSelected:         'None selected',
  highlights:           'Highlights',
  shadows:              'Shadows',
  color:                'Color',
  untitled:             'Untitled',
  columns:              'Columns',
  save:                 'Save',
  accent:               'Accent',
  applying:             'Applying',
  viewing:              'Viewing',
  clearMessages:        'Clear messages',
  clearNextMessages:    'Clear next messages',
  apply:                'Apply',
  import:               'Import',
  search:               'Search...',
  where:                'Where',
  noTimeArray:          'No time array',
  success:              'Success',
  error:                'Error',
  warning:              'Warning',
  attach:               'Attach',
  attachImage:          'Attach Image',
  actions:              'Actions',
  addNewColumn:         'Add new column',
  addNewRow:            'Add new row',
  addFilter:            'Add filter',
  addSort:              'Add sort',
  applySorting:         'Apply sorting',
  applyFilters:         'Apply filters',
  filter:               'Filter',
  sort:                 'Sort',
  resetFilters:         'Reset filters',
  resetSorting:         'Reset sorting',
  description:          'Description',
  name:                 'Name',
  loremIpsumSmall:      'Lorem ipsum dolor sit amet.',
  loremIpsumMedium:     'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus ac libero vehicula ultricies.',
  loremIpsumLong:       'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus ac libero vehicula ultricies. Nulla facilisi. Sed nec nisl in turpis tincidunt tincidunt. Nulla facilisi. Sed nec nisl in turpis tincidunt tincidunt.',
  selectAgent:          'Select Agent',
  selectModel:          'Select Model',
  sendPrompt:           'Send Prompt',
  view:                 'View',
  toggleColumns:        'Toggle columns',
  toggleOpen:           'Toggle open',
  reset:                'Reset',
  noResultsFound:       'No results found.',
  clearFilters:         'Clear filters',
  rowsPerPage:          'Rows per page',
  id:                   'Id',
  noSortsTitle:         'No sorts apply to this view',
  noSortsDescription:   'Add a column below to sort the view',
  noFiltersTitle:       'No filters apply to this view',
  noFiltersDescription: 'Add a column below to filter the view',
  defaultValue:         'Default value',
  default:              'Default',
  stepDuration:         'Step duration (ms)',
  min:                  'Min',
  max:                  'Max',
  icon:                 'Icon',
  step:                 'Step',
  decimals:             'Decimals',
  units:                'Units',
  play:                 'Play',
  pause:                'Pause',
  next:                 'Next',
  previous:             'Previous',
  loop:                 'Loop',
  rewind:               'Rewind',
  forward:              'Forward',
  start:                'Start',
  emptyCode:            'Select a file to view its content',
  generate:             'Generate',
  savePreset:           'Save Preset',
  image:                'Image',
};
